require 'weary'
require 'steam-api/version'
require 'steam-api/steam'
require 'steam-api/steam/user'
#require 'steam-api/apps'
#require 'steam-api/economy'
#require 'steam-api/player'
#require 'steam-api/remote_storage'
#require 'steam-api/user_stats'

